### ISSUE TITLE
splitting is not empty error

### ISSUE THREAD

**Issue by imochurad** [dajobe/hbase-docker#15]
Following issue seen in the container log, what does it indicate and how it could be resolved? 

```
hbase-docker_1  | 2016-12-12 10:34:45,115 WARN  [ProcedureExecutor-2] master.SplitLogManager: Returning success without actually splitting and deleting all the log files in path file:/data/hbase/WALs/hbase-docker,43924,1481521767704-splitting: [DeprecatedRawLocalFileStatus{path=file:/data/hbase/WALs/hbase-docker,43924,1481521767704-splitting/hbase-docker%2C43924%2C1481521767704..meta.1481525378577.meta; isDirectory=false; length=83; replication=1; blocksize=33554432; modification_time=1481525378000; access_time=0; owner=; group=; permission=rw-rw-rw-; isSymlink=false}]
hbase-docker_1  | java.io.IOException: Directory /data/hbase/WALs/hbase-docker,43924,1481521767704-splitting is not empty
hbase-docker_1  | 	at org.apache.hadoop.fs.RawLocalFileSystem.delete(RawLocalFileSystem.java:360)
hbase-docker_1  | 	at org.apache.hadoop.fs.ChecksumFileSystem.delete(ChecksumFileSystem.java:540)
hbase-docker_1  | 	at org.apache.hadoop.hbase.master.SplitLogManager.splitLogDistributed(SplitLogManager.java:296)
hbase-docker_1  | 	at org.apache.hadoop.hbase.master.MasterFileSystem.splitLog(MasterFileSystem.java:398)
hbase-docker_1  | 	at org.apache.hadoop.hbase.master.MasterFileSystem.splitLog(MasterFileSystem.java:371)
hbase-docker_1  | 	at org.apache.hadoop.hbase.master.MasterFileSystem.splitLog(MasterFileSystem.java:293)
hbase-docker_1  | 	at org.apache.hadoop.hbase.master.procedure.ServerCrashProcedure.splitLogs(ServerCrashProcedure.java:438)
hbase-docker_1  | 	at org.apache.hadoop.hbase.master.procedure.ServerCrashProcedure.executeFromState(ServerCrashProcedure.java:251)
hbase-docker_1  | 	at org.apache.hadoop.hbase.master.procedure.ServerCrashProcedure.executeFromState(ServerCrashProcedure.java:73)
hbase-docker_1  | 	at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:119)
hbase-docker_1  | 	at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:498)
hbase-docker_1  | 	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1061)
hbase-docker_1  | 	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:856)
hbase-docker_1  | 	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:809)
hbase-docker_1  | 	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$400(ProcedureExecutor.java:75)
hbase-docker_1  | 	at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$2.run(ProcedureExecutor.java:495)
```

**Comment by jacarrichan** [comment]
should  fix it ~~~
