### ISSUE TITLE
Can't connect with Java client

### ISSUE THREAD

**Issue by hellowin** [dajobe/hbase-docker#5]
Is this my only problems or there are something wrong? I use Java client. In my HBase Master Status Web UI My Zookeeper looks like "Zookeeper Quorum	10.0.2.15:2181" is that exposed to my docker host?

```
INFO client.HConnectionManager$HConnectionImplementation: getM
aster attempt 7 of 14 failed; retrying after sleep of 8035
java.net.UnknownHostException: unknown host: boot2docker
        at org.apache.hadoop.hbase.ipc.HBaseClient$Connection.<init>(HBaseClient
.java:277)
        at org.apache.hadoop.hbase.ipc.HBaseClient.createConnection(HBaseClient.
java:256)
        at org.apache.hadoop.hbase.ipc.HBaseClient.getConnection(HBaseClient.jav
a:1128)
        at org.apache.hadoop.hbase.ipc.HBaseClient.call(HBaseClient.java:988)
        at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Invoker.invoke(Writable
RpcEngine.java:87)
        at com.sun.proxy.$Proxy6.getProtocolVersion(Unknown Source)
        at org.apache.hadoop.hbase.ipc.WritableRpcEngine.getProxy(WritableRpcEng
ine.java:141)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplemen
tation.getMaster(HConnectionManager.java:813)
        at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:127)

        at id.nolimit.platform.store.injector.HBaseTable.<init>(HBase.scala:28)
        at id.nolimit.platform.store.injector.HBaseRawTable.<init>(HBaseTables.s
cala:3)
        at id.nolimit.platform.store.injector.Injector$.mainInjector(Injector.sc
ala:16)
        at id.nolimit.platform.store.actor.JsonWorker.id$nolimit$platform$store$
actor$JsonWorker$$store(StoreWorker.scala:159)
        at id.nolimit.platform.store.actor.JsonWorker$$anonfun$receive$2.applyOr
Else(StoreWorker.scala:186)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at id.nolimit.platform.store.actor.JsonWorker.aroundReceive(StoreWorker.
scala:134)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)
```

**Comment by hellowin** [comment]
it's not happen when I use Linux, I will solve this maybe because of boot2docker
